# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}