# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  model:
    description: 'model id'
    required: true
  language:
    description: 'The language for the prediction'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.model }}
    - ${{ inputs.language }}